# Generated by Django 5.0.3 on 2024-04-04 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_category_user_role'),
        ('core', '0002_alter_courses_user_alter_jobs_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='category',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='category',
        ),
        migrations.AddField(
            model_name='courses',
            name='course_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_category', to='accounts.category'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_category', to='accounts.category'),
        ),
        migrations.AddField(
            model_name='trainings',
            name='training_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_category', to='accounts.category'),
        ),
    ]
