# Generated by Django 5.0.3 on 2024-04-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_courses_category_remove_jobs_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesteps',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
