# Generated by Django 5.0.3 on 2024-04-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_coursesteps_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainings',
            name='category',
        ),
    ]
