# Generated by Django 5.0.3 on 2024-04-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_category_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Trainer', 'Trainer'), ('Institute', 'Institute')], default='Student', max_length=100, null=True),
        ),
    ]
